### ISSUE TITLE
Winter Storage - Design

### ISSUE THREAD

**Issue by ccmorris** [CCI-Studios/Otools-2015#4]

**Comment by ianfader** [comment]
Design is on file server:

Working > Inner Pages > Winter Storage >

**Comment by ccmorris** [comment]
The Supreme Gas package is very different from the electric package in the description. eg. "oil change, replacement of spark plug(s) & all filters, test carburetor" ...

I could add that paragraph as well, but then it is not much different from the current page.

How about this, we pull out the parts that repeated verbatim in each package. Then we have 2 headings for Basic and Supreme, and in each of those we have headings for Gas and Electric. I also just noticed that the Basic Gas is exactly the same as Basic Electric. Let's combine those.

you will be notified of spring return by blah ...
BASIC
 package includes pickup & delivery...
  GAS/ELECTRIC $175
SUPREME
 bumper-to-bumper service ...
  ELECTRIC $225
   discharge test battery blah blah...
  GAS $265
   oil change, replacement of spark plug(s) & all filters, test carburetor...

**Comment by ccmorris** [comment]
There should also be a link to the winter storage form

**Comment by ccmorris** [comment]
The link is in your design. Nevermind!
