### ISSUE TITLE
Create a page with an email signup that links to the MailChimp list

### ISSUE THREAD

**Issue by ianfader** [CCI-Studios/Otools-2015#68]
Fields:
- Name
- Email Address
- Checkbox for express consent
- Submit Button

**Comment by ccmorris** [comment]
http://otools.ccistaging.com/otools-newsletter

**Comment by ianfader** [comment]
Can the email address be removed or changed at the bottom of the confirm message?

![screen shot 2017-04-10 at 3 45 39 pm](https://cloud.githubusercontent.com/assets/8989188/24879421/d950fed0-1e04-11e7-9dc9-e5a8e951fd3f.png)

**Comment by ccmorris** [comment]
That Newsletter list in Mailchimp must be soo old. I updated the email address for the list. You can also change all of the content in this confirmation email in Mailchimp. Open the O'tools Newsletter list, go to Signup forms, General forms, from the select dropdown go to Opt-in confirmation email.
