### ISSUE TITLE
Custom Cart Quote form - there are updates to the current form/page (psd file was sent)

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/Otools-2015#75]
http://www.otools.ca/custom-cart-quote

**Comment by ccmorris** [comment]
that's the live site

Maybe have a look on the staging site
http://otools.ccistaging.com/custom-cart-quote

**Comment by tgascoigne14** [comment]
Got it. The links in the menu link to a financing quote site and didn't think to look up the actual page lol sorry.
