### ISSUE TITLE
Cart Details Page - Features and Warranty info should be in collapsable sections and wrapping around the image area (like design)

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/Otools-2015#76]
![Screen Shot 2020-05-20 at 11 39 25 AM](https://user-images.githubusercontent.com/8631079/82466579-9a1f5680-9a8e-11ea-8cd6-9d4ccc1bdbb7.png)

**Comment by ccmorris** [comment]
The collapsible sections exist, when there is content.

I did one for demonstration with some content cut from the body here:
http://otools.ccistaging.com/carts/new/carryall-500-48v-utility-demo

**Comment by tgascoigne14** [comment]
S we have to update all of the existing carts on the site for this update?

**Comment by ccmorris** [comment]
Yes. The description was all in one field before, now there are three fields.

**Comment by tgascoigne14** [comment]
frig. okiedokiesmokie
