### ISSUE TITLE
Add Utility Carts Landing Page with cart listing and header content block

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/Otools-2015#80]
I can't figure out how to create a landing page for Utility Carts. I created the term in taxonomy area and was able to move the one utility cart into its own section but I don't know how to make the landing page like we have for the rest of the cart categories

**Comment by tgascoigne14** [comment]
@ccmorris I've added the cart that is available in the Utility Carts category - https://otools.ccistaging.com/carts/utility

I've added the header content for the area above the cart listing - https://otools.ccistaging.com/admin/structure/block/manage/block/29/configure?destination=taxonomy/term/130

I obviously need your help 👍

**Comment by ccmorris** [comment]
@tgascoigne14 yup. I just needed to make a page in the view for the utility carts.
Here it is https://otools.ccistaging.com/carts/utility-golf-carts
